### PR TITLE
updates dependencies

### PR DESCRIPTION
**Pull request by maxwellbenton**
Students experiencing many deprecation warnings due to learn-browser's dependencies. Mocha needs upgrade from 3.x -> 5.2.0 and a minor release upgrade is needed on browser-sync.

https://github.com/learn-co-curriculum/js-looping-and-iteration-filter-and-map-lab/issues/3

This update would affect a significant portion of current JS labs in the online and immersive tracks. A number of labs in JS have already been independently upgraded to mocha 5.2.0 without any need for code changes, so this should not have a negative impact on lab functionality.

### CODE REVIEW

**Review by gj — CHANGES_REQUESTED** [review]
Updating deps is fine, but let's stick w/ Yarn instead of NPM. There's already a `yarn.lock` file — no need for `package-lock.json`

**Comment by maxwellbenton** [comment]
whoops, my apologies. Swapped to yarn and removed `package-lock.json`

**Review by gj — APPROVED** [review]

**Comment by maxwellbenton** [comment]
Hey @gj,

I don't have write access on this repo. Would it be possible to merge this in or is there another step?

**Comment by gj** [comment]
@maxwellbenton I invited you to a new @learn-co/curriculum-team GitHub team that has write access to this repo. You'll also need publish access to the package on NPM, which I can grant if you give me your NPM username.

**Pull request merged**
